# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        PIGBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
      our_db_provider:
        entity:
          class: PIGBundle:User


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        usuarios:
            pattern: ^/*
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /usuarios/login
                check_path: /usuarios/login
                default_target_path: /usuarios
            logout:
                path:   /usuarios/logout
                target: /usuarios

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
            - { path: ^/usuarios/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_USUARIO }
