pig_homepage:
    path:     /
    defaults: { _controller: PIGBundle:User:login }

clientes_index:
    path:     /clientes
    defaults: { _controller: PIGBundle:Cliente:index }

clientes_nuevo:
    path:     /clientes/new
    defaults: { _controller: PIGBundle:Cliente:nuevoCliente }

clientes_todos:
    path:     /clientes/all
    defaults: { _controller: PIGBundle:Cliente:clienteAll }

clientes_show:
    path:     /clientes/show/{id}
    defaults: { _controller: PIGBundle:Cliente:clienteShow }

clientes_exito:
    path:     /clientes/msgExito
    defaults: { _controller: PIGBundle:Cliente:msgExito }

trabajadoras_index:
    path:     /trabajadoras
    defaults: { _controller: PIGBundle:Trabajadora:index }

trabajadoras_nueva:
    path:     /trabajadoras/new
    defaults: { _controller: PIGBundle:Trabajadora:nuevaTrabajadora }

trabajadoras_todas:
    path:     /trabajadoras/show/{id}
    defaults: { _controller: PIGBundle:Trabajadora:trabajadoraShow }

trabajadoras_exito:
    path:     /trabajadoras/msgExito
    defaults: { _controller: PIGBundle:Trabajadora:msgExito }


Servicios_index:
    path:     /servicios
    defaults: { _controller: PIGBundle:Servicio:index }

Servicios_nuevo:
    path:     /servicios/new
    defaults: { _controller: PIGBundle:Servicio:nuevoServicio }

Servicios_todos:
    path:     /servicios/all
    defaults: { _controller: PIGBundle:Servicio:servicioAll }

Servicios_show:
    path:     /servicios/show/{id}
    defaults: { _controller: PIGBundle:Servicio:servicioShow }

Servicios_exito:
    path:     /servicios/msgExito
    defaults: { _controller: PIGBundle:Servicio:msgExito }

Otros_nuevo:
    path:     /servicios/newOtro
    defaults: { _controller: PIGBundle:Otro:nuevoOtro }

Mantenimientos_nuevo:
    path:     /servicios/newMantenimiento
    defaults: { _controller: PIGBundle:Mantenimiento:nuevoMantenimiento }

Caterings_nuevo:
    path:     /servicios/newCatering
    defaults: { _controller: PIGBundle:Catering:nuevoCatering }

Limpiezas_nuevo:
    path:     /servicios/newLimpieza
    defaults: { _controller: PIGBundle:Limpieza:nuevoLimpieza }

usuario_nuevo:
    path:     /register
    defaults: { _controller: PIGBundle:User:register }

usuarios_homepage:
    path:     /usuarios
    defaults: { _controller: PIGBundle:Default:index }

login:
    path:     /usuarios/login
    defaults: { _controller: PIGBundle:User:login}
