<?php

namespace Proxies\__CG__\PIGBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Trabajadora extends \PIGBundle\Entity\Trabajadora implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'servicio', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'id', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'nombre', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'apellidos', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'direccion', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'fechaAlta', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'puesto', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'noCuentaBanco', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'noSeguridadSocial', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'dNI', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'fechaNac', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'telefono', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'estado'];
        }

        return ['__isInitialized__', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'servicio', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'id', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'nombre', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'apellidos', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'direccion', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'fechaAlta', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'puesto', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'noCuentaBanco', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'noSeguridadSocial', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'dNI', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'fechaNac', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'telefono', '' . "\0" . 'PIGBundle\\Entity\\Trabajadora' . "\0" . 'estado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Trabajadora $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', [$apellidos]);

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', []);

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuesto($puesto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuesto', [$puesto]);

        return parent::setPuesto($puesto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuesto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuesto', []);

        return parent::getPuesto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCuentaBanco($noCuentaBanco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCuentaBanco', [$noCuentaBanco]);

        return parent::setNoCuentaBanco($noCuentaBanco);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCuentaBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCuentaBanco', []);

        return parent::getNoCuentaBanco();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoSeguridadSocial($noSeguridadSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoSeguridadSocial', [$noSeguridadSocial]);

        return parent::setNoSeguridadSocial($noSeguridadSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoSeguridadSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoSeguridadSocial', []);

        return parent::getNoSeguridadSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setDNI($dNI)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDNI', [$dNI]);

        return parent::setDNI($dNI);
    }

    /**
     * {@inheritDoc}
     */
    public function getDNI()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDNI', []);

        return parent::getDNI();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNac($fechaNac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNac', [$fechaNac]);

        return parent::setFechaNac($fechaNac);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNac', []);

        return parent::getFechaNac();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function addServicio(\PIGBundle\Entity\Servicio $servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addServicio', [$servicio]);

        return parent::addServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeServicio(\PIGBundle\Entity\Servicio $servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeServicio', [$servicio]);

        return parent::removeServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicio', []);

        return parent::getServicio();
    }

}
