<?php

namespace Proxies\__CG__\PIGBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cliente extends \PIGBundle\Entity\Cliente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'servicio', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'nombre', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'cIF', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'domicilioFiscal', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'cP', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'municipio', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'provincia', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'noCuentaBancaria', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'personaContacto', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'telefonoContacto', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'telefonoMovilContacto', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'razonSocial'];
        }

        return ['__isInitialized__', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'servicio', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'nombre', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'cIF', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'domicilioFiscal', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'cP', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'municipio', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'provincia', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'noCuentaBancaria', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'personaContacto', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'telefonoContacto', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'telefonoMovilContacto', '' . "\0" . 'PIGBundle\\Entity\\Cliente' . "\0" . 'razonSocial'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cliente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function setCIF($cIF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCIF', [$cIF]);

        return parent::setCIF($cIF);
    }

    /**
     * {@inheritDoc}
     */
    public function getCIF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCIF', []);

        return parent::getCIF();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilioFiscal($domicilioFiscal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilioFiscal', [$domicilioFiscal]);

        return parent::setDomicilioFiscal($domicilioFiscal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilioFiscal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilioFiscal', []);

        return parent::getDomicilioFiscal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCP($cP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCP', [$cP]);

        return parent::setCP($cP);
    }

    /**
     * {@inheritDoc}
     */
    public function getCP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCP', []);

        return parent::getCP();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio($municipio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', [$municipio]);

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', []);

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia($provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', [$provincia]);

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', []);

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCuentaBancaria($noCuentaBancaria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCuentaBancaria', [$noCuentaBancaria]);

        return parent::setNoCuentaBancaria($noCuentaBancaria);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCuentaBancaria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCuentaBancaria', []);

        return parent::getNoCuentaBancaria();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonaContacto($personaContacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonaContacto', [$personaContacto]);

        return parent::setPersonaContacto($personaContacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonaContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonaContacto', []);

        return parent::getPersonaContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoContacto($telefonoContacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoContacto', [$telefonoContacto]);

        return parent::setTelefonoContacto($telefonoContacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoContacto', []);

        return parent::getTelefonoContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoMovilContacto($telefonoMovilContacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoMovilContacto', [$telefonoMovilContacto]);

        return parent::setTelefonoMovilContacto($telefonoMovilContacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoMovilContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoMovilContacto', []);

        return parent::getTelefonoMovilContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazonSocial($razonSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazonSocial', [$razonSocial]);

        return parent::setRazonSocial($razonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazonSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazonSocial', []);

        return parent::getRazonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function addServicio(\PIGBundle\Entity\Servicio $servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addServicio', [$servicio]);

        return parent::addServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeServicio(\PIGBundle\Entity\Servicio $servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeServicio', [$servicio]);

        return parent::removeServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicio', []);

        return parent::getServicio();
    }

}
