<?php

namespace Proxies\__CG__\PIGBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Servicio extends \PIGBundle\Entity\Servicio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'cliente', 'trabajadora', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'id', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'personaContacto', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'telefonoContacto', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'direccion', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'fecha', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'observaciones', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'estado', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'tipo'];
        }

        return ['__isInitialized__', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'cliente', 'trabajadora', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'id', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'personaContacto', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'telefonoContacto', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'direccion', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'fecha', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'observaciones', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'estado', '' . "\0" . 'PIGBundle\\Entity\\Servicio' . "\0" . 'tipo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Servicio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonaContacto($personaContacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonaContacto', [$personaContacto]);

        return parent::setPersonaContacto($personaContacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonaContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonaContacto', []);

        return parent::getPersonaContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoContacto($telefonoContacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoContacto', [$telefonoContacto]);

        return parent::setTelefonoContacto($telefonoContacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoContacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoContacto', []);

        return parent::getTelefonoContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\PIGBundle\Entity\Cliente $cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', [$cliente]);

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function addTrabajadora(\PIGBundle\Entity\Trabajadora $trabajadora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTrabajadora', [$trabajadora]);

        return parent::addTrabajadora($trabajadora);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTrabajadora(\PIGBundle\Entity\Trabajadora $trabajadora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTrabajadora', [$trabajadora]);

        return parent::removeTrabajadora($trabajadora);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrabajadora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrabajadora', []);

        return parent::getTrabajadora();
    }

    /**
     * {@inheritDoc}
     */
    public function addServicio(\PIGBundle\Entity\Trabajadora $servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addServicio', [$servicio]);

        return parent::addServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeServicio(\PIGBundle\Entity\Trabajadora $servicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeServicio', [$servicio]);

        return parent::removeServicio($servicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicio', []);

        return parent::getServicio();
    }

}
